const sourceUrl = "https://github.com/rainco2008/https-github.com-rainco2008-it-tools";

const definitions: Array<[string, string, string, string, string[]]> = [
  ["hash-generator", "Hash Generator", "Crypto & Security", "Generate MD5, SHA-1, SHA-256 and SHA-512 hashes from text.", ["hash", "md5", "sha256"]],
  ["bcrypt-tool", "Bcrypt Hash & Verify", "Crypto & Security", "Generate and compare passwords with salted Bcrypt hashes.", ["bcrypt", "password", "security"]],
  ["hmac-generator", "HMAC Generator", "Crypto & Security", "Generate keyed-hash message authentication codes.", ["hmac", "signature", "authentication"]],
  ["encryption-tool", "Encryption / Decryption", "Crypto & Security", "Encrypt and decrypt text with common client-side ciphers.", ["aes", "encrypt", "decrypt"]],
  ["jwt-parser", "JWT Token Parser", "Crypto & Security", "Decode JWT headers and payloads and inspect expiration.", ["jwt", "token", "auth"]],
  ["uuid-generator", "UUID Generator", "Crypto & Security", "Batch-generate UUID identifiers in the browser.", ["uuid", "guid", "identifier"]],
  ["ulid-generator", "ULID Generator", "Crypto & Security", "Generate sortable ULID identifiers.", ["ulid", "sortable", "identifier"]],
  ["basic-auth", "Basic Auth Generator", "Crypto & Security", "Generate HTTP Basic Authentication headers.", ["basic auth", "http", "header"]],
  ["base64-string", "Base64 String Converter", "Converters", "Encode and decode Base64 strings.", ["base64", "encode", "decode"]],
  ["base64-file", "Base64 File Converter", "Converters", "Convert local files into Base64 data URI strings.", ["base64", "file", "data uri"]],
  ["datetime-converter", "Date-Time & Epoch Converter", "Converters", "Convert Unix timestamps and date-time values.", ["timestamp", "epoch", "date"]],
  ["case-converter", "Case Converter", "Converters", "Transform text between common naming conventions.", ["camelCase", "snake_case", "kebab-case"]],
  ["color-converter", "Color Converter", "Converters", "Convert and preview HEX, RGB, HSL, HSV and CMYK colors.", ["color", "hex", "rgb"]],
  ["integer-base", "Integer Base Converter", "Converters", "Convert integers between binary, octal, decimal, hexadecimal and Base36.", ["binary", "hex", "radix"]],
  ["url-encoder", "URL Encoder / Decoder", "Web & Network", "Encode or decode URLs and URI components.", ["url", "uri", "encode"]],
  ["url-parser", "URL Parser", "Web & Network", "Parse protocol, host, port, path and query parameters from a URL.", ["url", "hostname", "query"]],
  ["ipv4-subnet", "IPv4 Subnet Calculator", "Web & Network", "Calculate IPv4 network, broadcast and usable host ranges from CIDR.", ["ipv4", "subnet", "cidr"]],
  ["http-status", "HTTP Status Codes", "Web & Network", "Searchable reference for HTTP status codes and descriptions.", ["http", "status", "api"]],
  ["qr-code", "QR Code Generator", "Web & Network", "Generate QR codes for text, URLs and contact information.", ["qr", "barcode", "url"]],
  ["device-info", "Device & Browser Info", "Web & Network", "Inspect browser, screen, operating system and user-agent information.", ["device", "browser", "user agent"]],
  ["lorem-ipsum", "Lorem Ipsum Generator", "Text & Strings", "Generate placeholder text by paragraphs, sentences or words.", ["lorem", "placeholder", "dummy text"]],
  ["text-statistics", "Text Statistics & Counter", "Text & Strings", "Count characters, words, sentences, lines, bytes and reading time.", ["word count", "characters", "statistics"]],
  ["slugify", "String Slugifier", "Text & Strings", "Convert titles and strings into clean URL slugs.", ["slug", "seo", "url"]],
  ["html-entities", "HTML Entities Encoder", "Text & Strings", "Encode and decode HTML entities and special characters.", ["html", "entities", "escape"]],
  ["json-formatter", "JSON Prettify & Minify", "Formatters", "Validate, prettify and minify JSON data.", ["json", "format", "minify"]],
  ["sql-formatter", "SQL Query Prettifier", "Formatters", "Format SQL queries with readable indentation.", ["sql", "query", "database"]],
  ["xml-formatter", "XML Formatter", "Formatters", "Format XML strings with consistent indentation.", ["xml", "format", "soap"]],
  ["math-evaluator", "Math Expression Evaluator", "Math & Dev Tools", "Evaluate mathematical expressions and conversions.", ["math", "formula", "calculator"]],
  ["percentage-calculator", "Percentage Calculator", "Math & Dev Tools", "Calculate ratios, percentages, discounts and percentage changes.", ["percent", "ratio", "discount"]],
  ["crontab-generator", "Crontab Expression Generator", "Math & Dev Tools", "Build cron expressions and readable schedule explanations.", ["cron", "schedule", "timer"]],
  ["chmod-calculator", "Chmod Permission Calculator", "Math & Dev Tools", "Calculate Unix file permissions in octal and symbolic form.", ["chmod", "linux", "permissions"]],
  ["git-memo", "Git Cheatsheet", "Cheatsheets & Memos", "Searchable reference for common Git commands.", ["git", "commit", "branch"]],
  ["regex-memo", "Regex Cheatsheet & Tester", "Cheatsheets & Memos", "Reference and live tester for regular expressions.", ["regex", "regexp", "pattern"]],
  ["keycode-info", "Keycode Event Inspector", "Cheatsheets & Memos", "Inspect JavaScript keyboard event codes and properties.", ["keyboard", "keycode", "event"]]
];

export const DEVELOPMENT_TOOL_CATALOG = definitions.map(([id, name, subCategory, description, features]) => ({
  slug: `it-tools-${id}`,
  name: `IT Tools - ${name}`,
  category: "Development" as const,
  subCategory,
  industryAnchor: "IT Tools",
  description,
  overview: `${description} This browser-first utility was migrated into the newfreetools Development workbench and does not require a server-side API call.`,
  pros: ["Runs locally in the browser", "Integrated with the newfreetools Development category", "Open-source implementation"],
  cons: ["Advanced workflows may be limited compared with dedicated desktop tools", "Large inputs still depend on browser memory"],
  priceRange: "Open Source" as const,
  priceInfo: "Free and open source",
  officialUrl: sourceUrl,
  studioAlternativeId: "development-tools",
  trustScore: "High" as const,
  verified: true,
  features,
}));
